### ISSUE TITLE
Error installing mailman3 - failed to create network docker-mailman_mailman

### ISSUE THREAD

**Issue by odhiambo** [g4rf/dockerized-mailcow-mailman#10]
Hello admins,

I have gotten stuck installng mailman3 to integrate with mailcow-dockernized.
I get the following error:
```
root@panafcon-srv1:/opt/docker-mailman# docker compose up -d
[+] Running 1/1
 ✘ Network docker-mailman_mailman  Error                                                                                                                                                                             
failed to create network docker-mailman_mailman: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space
root@panafcon-srv1:/opt/docker-mailman#
```

I am following the guide at https://docs.mailcow.email/third_party/mailman3/third_party-mailman3/.
It says I create /opt/mailcow-dockerized/docker-compose.override.yml containing:
```
services:
  postfix-mailcow:
    volumes:
      - /opt/mailman:/opt/mailman
    networks:
      - docker-mailman_mailman

networks:
  docker-mailman_mailman:
    external: true
```

And it refers to https://github.com/g4rf/dockerized-mailcow-mailman  which also says I create the same file  /opt/mailcow-dockerized/docker-compose.override.yml - but in this case the volume spec is different:
```
services:
  postfix-mailcow:
    volumes:
      - /opt/mailman/core/var/data/:/opt/mailman/core/var/data/
    networks:
      - docker-mailman_mailman

networks:
  docker-mailman_mailman:
    external: true
```

Because I am a n00b with Docker, I am wondering about which volume spec I should use. Is it "/opt/mailman:/opt/mailman" or the "/opt/mailman/core/var/data/:/opt/mailman/core/var/data/"?

And what might be the cause of the error that I am getting??

Thank you in advance.
