### ISSUE TITLE
Mailcow without proxy

### ISSUE THREAD

**Issue by rkcreation** [g4rf/dockerized-mailcow-mailman#7]
Hi

I have achieved mailcow + mailman setup without the need of Apache reverse-proxy.
I instead use custom site on mailcow nginx, so certs are already handled by mailcow.

In `/opt/mailcow-dockerized` :

```bash
nano docker-compose.override.yml
```

```yml
services:
  postfix-mailcow:
    volumes:
      - /opt/mailman:/opt/mailman
    networks:
      - docker-mailman_mailman
  nginx-mailcow:
    volumes:
      - /opt/mailman:/opt/mailman
    networks:
      - docker-mailman_mailman

networks:
  docker-mailman_mailman:
    external: true
```

```bash
nano data/conf/nginx/mailman.conf
```

```conf
server {
  ssl_certificate /etc/ssl/mail/cert.pem;
  ssl_certificate_key /etc/ssl/mail/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256>  ssl_ecdh_curve X25519:X448:secp384r1:secp256k1;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;
  index index.php index.html;
  client_max_body_size 0;
  root /web;
  include /etc/nginx/conf.d/listen_plain.active;
  include /etc/nginx/conf.d/listen_ssl.active;
  server_name lists.bapla.cloud;
  server_tokens off;

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }

  if ($scheme = http) {
    return 301 https://$host$request_uri;
  }

  location /static/ {
    alias /opt/mailman/web/static/;
  }

  location /favicon.ico {
    alias /opt/mailman/web/static/hyperkitty/img/favicon.ico;
  }

  location / {
    uwsgi_pass mailman-web:8080;
    include uwsgi_params;
    client_max_body_size 0;
  }
}
```

All other thigs are same as tutorial. Could someone test and give some feedback about that ?

I find this way simpler, and works in more cases than proxying mailcow.
